apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: mateapp
spec:
  type: ClusterIP
  selector:
    app: mateapp
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
