apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: mateapp
spec:
  type: ClusterIP
  selector:
    app: mateapp
  ports:
    - name: port-1
      protocol: TCP
      port: 8081
      targetPort: 8080
    - name: port-2
      protocol: TCP
      port: 8085
      targetPort: 8080
    - name: port-3
      protocol: TCP
      port: 8083
      targetPort: 8080
