apiVersion: batch/v1
kind: CronJob
metadata:
 name: srv-cronjob
 namespace: mateapp
spec:
 schedule: "*/4 * * * *"
 concurrencyPolicy: Allow
 startingDeadlineSeconds: 100
 successfulJobsHistoryLimit: 10
 failedJobsHistoryLimit: 5
 jobTemplate:
   spec:
     template:
       spec:
         containers:
         - name: cronjob_pod
           image: busybox
           command:
           - /bin/sh
           - -c
           - curl todoapp-service:8081/api/health
         restartPolicy: OnFailure
