apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: daemon-pod
 namespace: mateapp
 labels:
   app: mateapp
spec:
 selector:
   matchLabels:
     app: mateapp
 template:
   metadata:
     labels:
       app: mateapp
   spec:
     containers:
     - name: mate-server-daemon
       image: ikulyk404/busyboxplus:curl
       command: ["/bin/sh", "-c", "while true; do curl http://todoapp-service:8081/api/health; sleep 5; done"]
       resources:
         requests:
           cpu: "100m"
           memory: "100Mi"
         limits:
           cpu: "200m"
           memory: "200Mi"
       ports:
       - containerPort: 80
         hostPort: 30008
