apiVersion: v1
kind: Service
metadata:
  name: todoapp-nodeport
  namespace: mateapp
spec:
  type: NodePort
  selector:
    app: mateapp
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
    nodePort: 30007
